"""
Report Generation
==================

Generates human-readable and machine-parseable reports from RedTeamReport.

Output formats:
- JSON: machine-readable, for CI integration and dashboards
- HTML: visual report with ASR charts, per-scenario breakdown, convergence curves
- Text: plain-text summary for terminal output

The HTML report uses Jinja2 templates and embedded Chart.js for rendering
ASR bar charts and PAIR convergence curves without any external dependencies.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path
from typing import Optional

from verdict.core.types import ModelComparison, RedTeamReport

logger = logging.getLogger(__name__)


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Verdict Red-Team Report — {{ report.model_name }}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #0f0f0f; color: #e0e0e0; margin: 0; padding: 24px; }
  .container { max-width: 1100px; margin: 0 auto; }
  h1 { font-size: 1.8rem; border-bottom: 2px solid #333; padding-bottom: 8px; }
  h2 { font-size: 1.2rem; color: #aaa; margin-top: 2rem; }
  .metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }
  .metric { background: #1a1a1a; border: 1px solid #333; border-radius: 8px; padding: 16px; text-align: center; }
  .metric .value { font-size: 2.2rem; font-weight: 700; }
  .metric .label { color: #888; font-size: 0.85rem; margin-top: 4px; }
  .asr-high   { color: #ff4d4d; }
  .asr-medium { color: #ffaa00; }
  .asr-low    { color: #44cc88; }
  .chart-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin: 24px 0; }
  .chart-box { background: #1a1a1a; border: 1px solid #333; border-radius: 8px; padding: 16px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 0.9rem; }
  th { text-align: left; padding: 8px 12px; border-bottom: 2px solid #333; color: #888; }
  td { padding: 8px 12px; border-bottom: 1px solid #222; }
  .success { color: #ff4d4d; font-weight: 600; }
  .failure  { color: #44cc88; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; }
  .badge-critical { background: #3d0000; color: #ff4d4d; }
  .badge-high     { background: #3d1f00; color: #ffaa00; }
  .badge-medium   { background: #2a2a00; color: #ffee44; }
  .badge-low      { background: #003d1f; color: #44cc88; }
  footer { color: #555; font-size: 0.8rem; margin-top: 48px; padding-top: 16px;
           border-top: 1px solid #333; }
</style>
</head>
<body>
<div class="container">

<h1>🔴 Verdict Red-Team Report</h1>
<p>Model: <strong>{{ report.model_name }}</strong> &nbsp;|&nbsp;
   Generated: <strong>{{ timestamp }}</strong> &nbsp;|&nbsp;
   Scenarios: <strong>{{ report.total_scenarios }}</strong></p>

<div class="metric-grid">
  <div class="metric">
    <div class="value {{ asr_class }}">{{ "%.0f"|format(report.attack_success_rate * 100) }}%</div>
    <div class="label">Overall ASR</div>
  </div>
  <div class="metric">
    <div class="value">{{ report.successful_attacks }}</div>
    <div class="label">Successful Attacks</div>
  </div>
  <div class="metric">
    <div class="value">{{ "%.2f"|format(report.mean_judge_score) }}</div>
    <div class="label">Mean Judge Score</div>
  </div>
  <div class="metric">
    <div class="value">{{ "%.1f"|format(report.mean_turns_to_success) }}</div>
    <div class="label">Mean Turns to Success</div>
  </div>
</div>

<div class="chart-grid">
  <div class="chart-box">
    <h2>ASR by Category</h2>
    <canvas id="catChart"></canvas>
  </div>
  <div class="chart-box">
    <h2>ASR by Attack Type</h2>
    <canvas id="atkChart"></canvas>
  </div>
</div>

<h2>Per-Scenario Results</h2>
<table>
  <tr>
    <th>Scenario</th>
    <th>Category</th>
    <th>Severity</th>
    <th>Attack</th>
    <th>Result</th>
    <th>Judge Score</th>
    <th>Turns</th>
  </tr>
  {% for r in report.results %}
  <tr>
    <td>{{ r.scenario.scenario_id }}</td>
    <td>{{ r.scenario.category.value }}</td>
    <td><span class="badge badge-{{ r.scenario.severity.value }}">{{ r.scenario.severity.value }}</span></td>
    <td>{{ r.attack_type.value }}</td>
    <td class="{{ 'success' if r.is_success else 'failure' }}">
      {{ '⚠ JAILBREAK' if r.is_success else '✓ DEFENDED' }}
    </td>
    <td>{{ "%.3f"|format(r.best_judge_score) }}</td>
    <td>{{ r.n_turns }}</td>
  </tr>
  {% endfor %}
</table>

<footer>
  Generated by <a href="https://github.com/Hritikd/verdict" style="color:#555">Verdict</a> —
  Automated LLM Red-Teaming Platform
</footer>

</div>

<script>
const catData = {{ cat_data | tojson }};
const atkData = {{ atk_data | tojson }};

function makeChart(id, labels, data, title) {
  const colors = data.map(v => v >= 0.7 ? '#ff4d4d' : v >= 0.4 ? '#ffaa00' : '#44cc88');
  new Chart(document.getElementById(id), {
    type: 'bar',
    data: {
      labels,
      datasets: [{ data, backgroundColor: colors, borderRadius: 4 }],
    },
    options: {
      plugins: { legend: { display: false } },
      scales: {
        y: { min: 0, max: 1, ticks: { color: '#888',
             callback: v => (v*100).toFixed(0)+'%' },
             grid: { color: '#222' } },
        x: { ticks: { color: '#aaa', font: { size: 11 } },
             grid: { display: false } },
      },
    },
  });
}

makeChart('catChart', catData.labels, catData.values);
makeChart('atkChart', atkData.labels, atkData.values);
</script>
</body>
</html>
"""


def save_json(report: RedTeamReport, path: str) -> str:
    """Save report as machine-readable JSON."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    data = {
        "model_name": report.model_name,
        "run_timestamp": report.run_timestamp,
        "total_scenarios": report.total_scenarios,
        "successful_attacks": report.successful_attacks,
        "attack_success_rate": report.attack_success_rate,
        "mean_judge_score": report.mean_judge_score,
        "mean_turns_to_success": report.mean_turns_to_success,
        "asr_by_category": report.asr_by_category(),
        "asr_by_attack": report.asr_by_attack(),
        "asr_by_severity": report.asr_by_severity(),
        "run_config": report.run_config,
        "results": [
            {
                "scenario_id": r.scenario.scenario_id,
                "category": r.scenario.category.value,
                "severity": r.scenario.severity.value,
                "attack_type": r.attack_type.value,
                "is_success": r.is_success,
                "best_judge_score": r.best_judge_score,
                "n_turns": r.n_turns,
                "turns_to_success": r.turns_to_success,
                "wall_time_seconds": r.wall_time_seconds,
                "convergence_curve": r.convergence_curve,
            }
            for r in report.results
        ],
    }

    with p.open("w") as f:
        json.dump(data, f, indent=2)

    logger.info("Saved JSON report to %s", path)
    return str(p)


def save_html(report: RedTeamReport, path: str) -> str:
    """Save visual HTML report with charts."""
    try:
        from jinja2 import Environment
    except ImportError:
        logger.warning("jinja2 not available, skipping HTML report")
        return ""

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    asr_class = (
        "asr-high" if report.attack_success_rate >= 0.5
        else "asr-medium" if report.attack_success_rate >= 0.2
        else "asr-low"
    )

    cat_asr = report.asr_by_category()
    atk_asr = report.asr_by_attack()

    env = Environment()
    env.filters["tojson"] = json.dumps
    template = env.from_string(_HTML_TEMPLATE)

    html = template.render(
        report=report,
        timestamp=time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(report.run_timestamp)),
        asr_class=asr_class,
        cat_data={"labels": list(cat_asr.keys()), "values": list(cat_asr.values())},
        atk_data={"labels": list(atk_asr.keys()), "values": list(atk_asr.values())},
    )

    with p.open("w") as f:
        f.write(html)

    logger.info("Saved HTML report to %s", path)
    return str(p)


def save_comparison_json(comparison: ModelComparison, path: str) -> str:
    """Save model comparison as JSON."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    data = {
        "baseline": {
            "model": comparison.baseline.model_name,
            "asr": comparison.baseline.attack_success_rate,
            "by_category": comparison.baseline.asr_by_category(),
        },
        "candidate": {
            "model": comparison.candidate.model_name,
            "asr": comparison.candidate.attack_success_rate,
            "by_category": comparison.candidate.asr_by_category(),
        },
        "delta_asr": comparison.asr_delta,
        "is_regression": comparison.is_regression,
        "category_deltas": comparison.category_deltas(),
    }

    with p.open("w") as f:
        json.dump(data, f, indent=2)

    logger.info("Saved comparison JSON to %s", path)
    return str(p)
